### ISSUE TITLE
Predict function error

### ISSUE THREAD

**Issue by kj-lai** [PatriciaRodrigues1994/Segmentation#1]
Hi, I tried to run your code, the training and fine-tuning section have no issues, but when I tried to run the prediction section for the test_images, there is an error.

![image](https://user-images.githubusercontent.com/34180949/75113473-3e108600-5689-11ea-804d-35af5001cb11.png)

This is the code I've used for prediction 
```
	parser.add_argument('--test_image_directory', type=str, default = "data/test_images")
        ...
	net = unet.UNet16()
	unet_classifier = classifier.UnetClassifier(net, args.fine_tune_epochs)
	if args.pred_on_inference_set:
		net.load_state_dict(torch.load(os.path.join(args.project_dir,'sum_logs/tb_logs/model.pt')))
		net = unet.freezing_pretrained_layers(model = net)
		origin_img_size = 224
		# # Predict & save
		classifier.predict(test_loader, callbacks=[pred_saver_cb])
		pred_saver_cb.close_saver()
```

IF i changed the 
`classifier.predict(test_loader, callbacks=[pred_saver_cb])` to
`unet_classifier.predict(test_loader, callbacks=[pred_saver_cb])`

it returns this error

![image](https://user-images.githubusercontent.com/34180949/75113667-c17ea700-568a-11ea-870a-8f4c54573a61.png)

**Comment by PatriciaRodrigues1994** [comment]
Hi,
   Thanks for pointing it out.
The issue was with volatile = True. I have pushed the code for this fix.
